### ISSUE TITLE
browser_control_dictacte

### ISSUE THREAD

**Issue by ssosas** [linto-ai/linto-skill-browser-control#1]
Hi all,

May you tell me where I can find an example of implementation for the browser_control_dictate regarding customer side? Ok I understand that the intent is handled by customerHandler function, but how to use the STT on the client to get the corresponding text?

Many thanks!

Sergio

**Comment by damienlaine** [comment]
See :
https://github.com/linto-ai/linto-web-client for generic client side implementation (exemples in tests/index.js)

This specific skill (linto-skill-browser-control) is used on a playground page on our future website, see next branch there : https://github.com/linto-ai/homepage-website/tree/next 
And especially the https://github.com/linto-ai/homepage-website/tree/next/playground folder where you'll find a full figured client-side implementation of this basic demonstration skill.
